# .github/workflows/ci-cd.yml

name: Static Site CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Validate HTML
      run: |
        # Install a simple HTML validator
        sudo apt-get install -y html-xml-utils
        # Validate the HTML file
        htmldoc --check hello.html

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to staging
      run: |
        echo "Deploying hello.html to staging environment"
        # For demonstration purposes, we'll just print the file contents
        cat hello.html
        # Here you would add deployment commands for your environment, like copying files to a server or a cloud service

